/* DO NOT EDIT THIS FILE - it is machine generated */


#ifndef _Included_com_xingchen_msgNotify_NotifyClient
#define _Included_com_xingchen_msgNotify_NotifyClient

#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
 
#ifndef IN
#define IN
#endif

#ifndef OUT
#define  OUT
#endif
 
unsigned long long  getCryptedWLanMAC
  (IN const unsigned char *  token,IN unsigned long long iMAC,IN int timestamp);

 
unsigned long long  decryptedWLanMAC
  (IN const  unsigned char *  token,IN  int  timestamp,IN  unsigned long long  cryptedMAC);

 
void createSecretKey //16位字节
  (OUT unsigned char * token);


void getCryptedPassword
  (IN unsigned long long iMAC,IN const char *  userName,IN const char *  password, IN int timestamp,IN const unsigned char * token,OUT char * cryptedPasswd);//iMAC随便设置一个mac地址  timestamp 当前时间 - 2010时间， cryptedPasswd密码33位



uint64_t cryptLongWithTimeStamp  (unsigned char * token, int timeStamp, uint64_t data);
uint64_t decryptLongWithTimeStamp (unsigned char * token, int timeStamp, uint64_t cryptedData);
uint64_t  cryptLong(unsigned char * token, uint64_t data);
uint64_t  decryptLong(unsigned char * token, uint64_t cryptedData);
  
#ifdef __cplusplus
}
#endif

#endif
